# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heartbeat_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'heartbeat_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17heartbeat_service.proto\x12\x02hb\x1a\x1bgoogle/protobuf/empty.proto\"1\n\nUptimeInfo\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x12\n\nuptime_sec\x18\x02 \x01(\x01\x32\x7f\n\x10HeartbeatService\x12\x36\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x33\n\tGetUptime\x12\x16.google.protobuf.Empty\x1a\x0e.hb.UptimeInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heartbeat_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPTIMEINFO']._serialized_start=60
  _globals['_UPTIMEINFO']._serialized_end=109
  _globals['_HEARTBEATSERVICE']._serialized_start=111
  _globals['_HEARTBEATSERVICE']._serialized_end=238
# @@protoc_insertion_point(module_scope)
