# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import object_repository_pb2 as object__repository__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in object_repository_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObjectRepositoryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterObject = channel.unary_unary(
                '/objectrepo.ObjectRepository/RegisterObject',
                request_serializer=object__repository__pb2.RegisterRequest.SerializeToString,
                response_deserializer=object__repository__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.DeregisterObject = channel.unary_unary(
                '/objectrepo.ObjectRepository/DeregisterObject',
                request_serializer=object__repository__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=object__repository__pb2.DeregisterResponse.FromString,
                _registered_method=True)
        self.UpdateObject = channel.unary_unary(
                '/objectrepo.ObjectRepository/UpdateObject',
                request_serializer=object__repository__pb2.UpdateRequest.SerializeToString,
                response_deserializer=object__repository__pb2.UpdateResponse.FromString,
                _registered_method=True)
        self.GetObject = channel.unary_unary(
                '/objectrepo.ObjectRepository/GetObject',
                request_serializer=object__repository__pb2.GetRequest.SerializeToString,
                response_deserializer=object__repository__pb2.GetResponse.FromString,
                _registered_method=True)
        self.ListObjects = channel.unary_unary(
                '/objectrepo.ObjectRepository/ListObjects',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=object__repository__pb2.ObjectListResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/objectrepo.ObjectRepository/Heartbeat',
                request_serializer=object__repository__pb2.HeartbeatPing.SerializeToString,
                response_deserializer=object__repository__pb2.HeartbeatAck.FromString,
                _registered_method=True)
        self.SyncState = channel.unary_unary(
                '/objectrepo.ObjectRepository/SyncState',
                request_serializer=object__repository__pb2.ObjectListResponse.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ObjectRepositoryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeregisterObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectRepositoryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterObject': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterObject,
                    request_deserializer=object__repository__pb2.RegisterRequest.FromString,
                    response_serializer=object__repository__pb2.RegisterResponse.SerializeToString,
            ),
            'DeregisterObject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeregisterObject,
                    request_deserializer=object__repository__pb2.DeregisterRequest.FromString,
                    response_serializer=object__repository__pb2.DeregisterResponse.SerializeToString,
            ),
            'UpdateObject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateObject,
                    request_deserializer=object__repository__pb2.UpdateRequest.FromString,
                    response_serializer=object__repository__pb2.UpdateResponse.SerializeToString,
            ),
            'GetObject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObject,
                    request_deserializer=object__repository__pb2.GetRequest.FromString,
                    response_serializer=object__repository__pb2.GetResponse.SerializeToString,
            ),
            'ListObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.ListObjects,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=object__repository__pb2.ObjectListResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=object__repository__pb2.HeartbeatPing.FromString,
                    response_serializer=object__repository__pb2.HeartbeatAck.SerializeToString,
            ),
            'SyncState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncState,
                    request_deserializer=object__repository__pb2.ObjectListResponse.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'objectrepo.ObjectRepository', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('objectrepo.ObjectRepository', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectRepository(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/RegisterObject',
            object__repository__pb2.RegisterRequest.SerializeToString,
            object__repository__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeregisterObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/DeregisterObject',
            object__repository__pb2.DeregisterRequest.SerializeToString,
            object__repository__pb2.DeregisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/UpdateObject',
            object__repository__pb2.UpdateRequest.SerializeToString,
            object__repository__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetObject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/GetObject',
            object__repository__pb2.GetRequest.SerializeToString,
            object__repository__pb2.GetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/ListObjects',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            object__repository__pb2.ObjectListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/Heartbeat',
            object__repository__pb2.HeartbeatPing.SerializeToString,
            object__repository__pb2.HeartbeatAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/objectrepo.ObjectRepository/SyncState',
            object__repository__pb2.ObjectListResponse.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
