# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: object_repository.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'object_repository.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17object_repository.proto\x12\nobjectrepo\x1a\x1bgoogle/protobuf/empty.proto\"q\n\x0fRegisterRequest\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x16\n\x0eobject_address\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x11\x44\x65registerRequest\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\"%\n\x12\x44\x65registerResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"o\n\rUpdateRequest\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x16\n\x0eobject_address\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\"!\n\x0eUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"!\n\nGetRequest\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\"%\n\x0bGetResponse\x12\x16\n\x0eobject_address\x18\x01 \x01(\t\"l\n\nObjectInfo\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12\x16\n\x0eobject_address\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\t\x12\x0e\n\x06region\x18\x05 \x01(\t\"=\n\x12ObjectListResponse\x12\'\n\x07objects\x18\x01 \x03(\x0b\x32\x16.objectrepo.ObjectInfo\"$\n\rHeartbeatPing\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\"\x1a\n\x0cHeartbeatAck\x12\n\n\x02ok\x18\x01 \x01(\x08\x32\xc0\x03\n\x10ObjectRepository\x12K\n\x0eRegisterObject\x12\x1b.objectrepo.RegisterRequest\x1a\x1c.objectrepo.RegisterResponse\x12Q\n\x10\x44\x65registerObject\x12\x1d.objectrepo.DeregisterRequest\x1a\x1e.objectrepo.DeregisterResponse\x12\x45\n\x0cUpdateObject\x12\x19.objectrepo.UpdateRequest\x1a\x1a.objectrepo.UpdateResponse\x12<\n\tGetObject\x12\x16.objectrepo.GetRequest\x1a\x17.objectrepo.GetResponse\x12\x45\n\x0bListObjects\x12\x16.google.protobuf.Empty\x1a\x1e.objectrepo.ObjectListResponse\x12@\n\tHeartbeat\x12\x19.objectrepo.HeartbeatPing\x1a\x18.objectrepo.HeartbeatAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_repository_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=68
  _globals['_REGISTERREQUEST']._serialized_end=181
  _globals['_REGISTERRESPONSE']._serialized_start=183
  _globals['_REGISTERRESPONSE']._serialized_end=218
  _globals['_DEREGISTERREQUEST']._serialized_start=220
  _globals['_DEREGISTERREQUEST']._serialized_end=260
  _globals['_DEREGISTERRESPONSE']._serialized_start=262
  _globals['_DEREGISTERRESPONSE']._serialized_end=299
  _globals['_UPDATEREQUEST']._serialized_start=301
  _globals['_UPDATEREQUEST']._serialized_end=412
  _globals['_UPDATERESPONSE']._serialized_start=414
  _globals['_UPDATERESPONSE']._serialized_end=447
  _globals['_GETREQUEST']._serialized_start=449
  _globals['_GETREQUEST']._serialized_end=482
  _globals['_GETRESPONSE']._serialized_start=484
  _globals['_GETRESPONSE']._serialized_end=521
  _globals['_OBJECTINFO']._serialized_start=523
  _globals['_OBJECTINFO']._serialized_end=631
  _globals['_OBJECTLISTRESPONSE']._serialized_start=633
  _globals['_OBJECTLISTRESPONSE']._serialized_end=694
  _globals['_HEARTBEATPING']._serialized_start=696
  _globals['_HEARTBEATPING']._serialized_end=732
  _globals['_HEARTBEATACK']._serialized_start=734
  _globals['_HEARTBEATACK']._serialized_end=760
  _globals['_OBJECTREPOSITORY']._serialized_start=763
  _globals['_OBJECTREPOSITORY']._serialized_end=1211
# @@protoc_insertion_point(module_scope)
